name: llama
channels:
  - pytorch
  - nvidia
  - conda-forge
  - huggingface
dependencies:
  - python=3.11
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=11.7
  - pip
  - pip:
    - tensorboard~=2.12
    - tqdm~=4.65
    - opendelta~=0.3.2
    - gdown~=4.7
    - mypy~=1.1
    - boto3~=1.18
    - botocore~=1.21
    - flake8~=6.0
    - gptq==0.0.3
    - deepspeed~=0.9.2
    - numba
    - jupyterlab
    - torch-summary
    - onnx-tf
    - pyworld
    - pandas
    - librosa
    - gitpython
    - cython
    - matplotlib
    - nltk
    - transformers

