name: pytorch-audio
channels:
  - pytorch
  - nvidia
  - conda-forge
  - huggingface
dependencies:
  - python=3.10
  - pytorch==1.13.1=py3.10_cuda11.7_cudnn8.5.0_0
  - torchvision=0.14.1
  - torchaudio=0.13.1
  - pytorch-cuda=11.7
  - pip=23.0
  - pip:
    - tensorboard~=2.12
    - tqdm~=4.65
    - opendelta~=0.3.2
    - gdown~=4.7
    - mypy~=1.1
    - boto3~=1.18
    - botocore~=1.21
    - flake8~=6.0
    - jupyterlab
    - torch-summary
    - speechbrain
    - soundfile
    - smmap
    - onnx-tf
    - pyworld
    - pandas
    - librosa
    - gitpython
    - cython
    - numba
    - matplotlib
    - nltk
