name: pytorch_train
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.8.13
  - pip=22.0.4
  - cudatoolkit=11.3
  - cudnn=8.3.2.44
  - yaml=0.2.5
  - numpy=1.21.6
  - umap-learn=0.5.3
  - pytorch==1.12.1=py3.8_cuda11.3_cudnn8.3.2_0
  - torchvision==0.13.1=py38_cu113
  - torchaudio==0.12.1=py38_cu113